api_version = "2024-07"

[[extensions]]
uid = "e40486c2-9c2b-c824-4822-6c2964ee608b18a4319a"
type = "theme"
name = "Recipe Widget"
handle = "recipe-widget"

[[extensions.blocks]]
type = "recipe-button"
name = "KOJIレシピ生成"
target = "body"
file = "blocks/recipe-button.liquid"